import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer";
import { Kanit } from "next/font/google";

const inter = Kanit({ subsets: ["latin"], weight: ["300"] });

export const metadata = {
  title: "Fin Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="body-container">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
