import "./globals.css";
import NavbarMain from "../components/navbar/NavbarMain";
import Footer from "../components/footer/Footer";
import Navbar from "../components/navbar/Navbar";

import { Text_Me_One } from "next/font/google";

const inter = Text_Me_One({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Fin Studio Architect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container">
          <NavbarMain />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
